#!/usr/bin/env python3

# Paste your email block below
raw_emails = """
info@kahler-berlin.de.
konditorei@rabien-berlin.de
kontakt@riedmair.de
info@eislabor.info.
Post@Kuchen-Torten-Berlin.de.
info@hofpfisterei.de
info@sarcletti.de.
info@konditorei-seidel.de
andre.knuepfer89@web.de
bauer-baeckerei@t-online.de.
trinis.konditorei@gmail.com.
info@meine-konditorei.de.
hermann@baeckerei-hermann.de.
info@konditorei-carlotta.de
verkauf@konditorei-heinemann.de.
wahlen@wermelskirchen.de
info@cafe-noe.de
Buero.UmOrdSGA@ba-pankow.berlin.de
info@wirtschaftskreis-pankow.de
Berlin@cafemelon.de.
shz-hattingen@caritas-ruhr-mitte.de.
info@pottery-art-cafe.de.
bistro@bulle-baeckerei.de.
mail@baeckerei-sickinger.de.
info@evertzberg.de.
info@villip-mitte.de.
info@biotillmann.de.
museum@alte-baeckerei-pankow.de
ks@winback.de.
office@ployer.at
bistro@bulle-baeckerei.de.
info@toros-baeckerei.de.
kontakt@urlaub-in-der-mitte.de
info@biodumaroc.de
info@baeckerei-hardt.de
info@baeckerei-zaman.de
ferien@cia-spandau.de
ordnungsamt@charlottenburg-wilmersdorf.de
info@biotillmann.de.
kontakt@linksfraktion-ts.dePrzejd
impressum@konditorei-laufer.de.
werner.jahn@axa.de
info@biesdorf-center.de
werner.jahn@axa.de
lichtenberg@kick-projekt.de.
baerbel.olhagaray@lichtenberg.berlin.de
ulf.wilhelm@spd-fraktion-reinickendorf.de
info@seehotel-lichtenberg.de.
info@biesdorf-center.de
impressum@konditorei-laufer.de
Eis-semmler@t-online.de
eiscafe.eiskoenigin@gmail.com.
baeckereigriesbach@web.de
grace.adenmosun@getu-prospects.de.
info@spd-reinickendorf.de.
kst-lichtenberg@volkssolidaritaet.de.Skip
info@urbanis-berlin.de
contact@teatrstudio.de
Charlottenburg-Wilmersdorf@jobpoint-berlin.de.
museum@charlottenburg-wilmersdorf.de
tiefbau@charlottenburg-wilmersdorf.de
info@guthesterberg.de
neef-confiserie@gmx.de
baeckerei_schroeter@gmx.de
support.de@quandoo.com
lissy-backt@web.de
info@elisa-konditorei.com
kontakt@naschhafen.de
kontakt@backerei-wiedenroth.de
info@diezuckerbaeckerin.com
konditorei-weber@t-online.de
info@konditorei-horn.de
info@halal-torten-hamburg.de
torten-viktori@web.de
dileksugarart@web.de
info@hansen-backerei.de
info@baeckerei-hillert.de
info@gasthaus-zur-post-cranz.de
info@cakesandcrumbsbyelke.de
info@hansen-baeckerei.de
info@emmas-hamburg.de
info@kleine-konditorei.com
info@conditorei-christiansen.de
info@baeckerei-bohnenkamp.de
condi.hvj@fairmont.com
info@trendbuero.de
mail@hafencity-map.de
info@niko-confiserie.de
info@datbackhus.de
zaubertrank@zaubertrank-hamburg.de
info@derbrotkorb.com
info@maison-mariee.com
gf@ribling.de
volker.klein@edeka-wedel.de
info@spanisches-mahl.de
info@daube-backt.de
kontakt@DasCafehaus.de
kontakt@dascafehaus.de
info@villa-volksdorf.de
info@dukatz.de
CafeMische@aol.com
info@johannatorten.de
info@sweetlab.de
info@cafe-grass.de
trau-dich-torte@gmx.de
info@goldstueck-muenchen.de
versand@kreutzkamm.de
info@pralinen-zauberei.de
info@konditorei-detterbeck.de
service@i-love-kuchen.de
luettmerding@tortenkreationen.de
info@gregormarx.com
info@kuchensucht.de
info@sepps-backstubn.de
die.konditormeisterin@live.de
kontakt@riedmair.de
info@ratschillers.de
info@baeckerei-neulinger.de
cafe@konditorei-widmann.de
zentrale@baeckerei-ziegler.de
info@bruecklmaier.de
info@rackls-backstubn.de
kontakt@schuhmair.de
info@baeckerei-seidl.de
kundenservice@mauerer.de
info@baeckerei-sickinger.de
info@zoettl.de
d.braner@muenchner-freiheit.de
stemerowitzgmbh@web.de
info@www.bruecklmaier.de
info@traublinger.de
kontakt@conditorei-rong.de
info@cafe-wahlen.de
info@cafe-fromme.net
mauel@mauel1883.de
voosen-ohg@t-online.de
info@baeckereipelzer.de
sabine.heisters@baeckerei-heisters.de
info@torten-taxi-koeln.de
kontakt@hans-gerd-kuhl.de
info@novisserie.de
info@jochenopitz.de
info@caketales.de
info@das-genusswerk.de
info@heidinger.org
info@estrela-doce.de
info@schaan.de
kontakt@grafs-cafe.de
kontakt@baeckerei-gangel.de
info@baeckerei-seipler.de
DortmundDeutschlandbaeckerei.vorwerk@t-online.de
info@niehaves.de
baeckerei.vorwerk@t-online.de
info@vorwerk-dortmund.de
info@malzers.de
info@konditorei-meister-lampe.de
info@gelsomino.de
BaeckereiCafeDressler@gmx.de
info@hafendoerfer.com
info@voss-baeckerei.de
baeckerei.troelsch@troelsch.de
dsb.jenny.menkhaus@it-s-me.com
brezelfrank@gmx.de
kondi.klaus@arcor.de
info@baeckerei-buerkle.de
info@baeckerei-sailer.de
kontakt@lidl.de
mail@baeckerei-heumaden.de
elke.rahm@t-online.de
info@baeckerei-schrade.de
info@von-rein.de
info@baeckerei-treiber.de
info@baeckerei-saur-fellbach.de
info@baeckerei-bausch.dehttps
mail@koenigsbau-cafe.de
pnsrxnaqyre@g-bayvar.qr
post@konditor-exklusiv.de
info@tausendtorten.de
info@baeckerei-goebecke.de
kontakt@corsoela.de
info@friedemann-leipzig.de
info@baeckerei-kleinert.de
baeckerei_tippner@gmx.de
info@baeckerei-herzog.dewww.baeckerei-herzog.de
Leisniginfo@muenchs-backstube.de
CafeKandler@cafekandler.de
die-genusswerkstatt@t-online.de
info@fraeulein-gusti.de
info@kleine-tortenstube.de
cafe-neuer@web.de
info@doellner.net
info@cafebeer.de
info@konditorei-rittinghausen.de
info@steingruber.de
baeckerei@woitinek.com
info@baeckerei-wild.de
guenter.ebenritter@arcor.de
samancu.konditorei@web.de
info@baeckerei-fuchs.de
info@ertels-backstube.de
info@baeckerei-nusselt.de
kontakt@konditormeisterinjulianazaspel.de
info@baeckerei-krebs.de
info@gradel.com
info@missfein.de
kontakt@stollenmanufaktur.de
info@cafe-maass.de
info@cafe-eisold.de
info@baeckerei-laube.de
info@stadtbaecker-saeurig.de
info@christstollen-chronik.de
ofenfrisch@baeckerei-krause.de
info@muehlenbaecker.de
geschaeftsleitung@unser-baecker.de
mail@konditorei-heller.de
info@baeckereiundkonditorei-hauer.de
baeckerei-krahl@t-online.de
kontakt@baeckerei-schwerdtner.de
lecker@konditorei-bierbaum.de
info@baeckerei-claus.de
dresden@konditorei-zscheile.de
info@dresdner-christstollen24.de
info@konditorei-kreipe.de
info@goeing.deUMSATZSTEUERUmsatzsteuer
383830E-Mailinfo@thiele.infoProdukteBroteBr
info@baeckereiborchers.de
info@baeckerei-raute.de
baeckereivormann@aol.com
luciankabell@yahoo.de
thzibo@gmail.com
info@transkiy.de
info@haala-fortriede.de
info@baeckerei-ernsting.de
info@holtumerland.de
buero@baeckerei-ruwe.de
info@lamm-mein-baecker.deRegistereintrag
info@ex.cominschildesche.deTelefonnummer
info@cafehaus-kleimann.de
info@schloss-cafe-poppelsdorf.de
228-92968817info@zuckermaedchens.de
info@zimmermanns-bonn.de
huenten@gmx.net
info@baeckerei-konditorei-schell.de
webmaster@broehl.net
kontakt@baeckerei-schaefer.de
mail@broehl.net
webmaster@baeckerei-panzer.de
info@gilgens.de
info@baeckerei-voigt.de
info@schnoorkonditorei.de
vedeDeutschlandwww.hoyer.deinfo@hoyer.deKontaktformularPartnerPowertrustSonnentau
kontakt@zimmermanngmbh.de
kontakt@bruene-meyer.de
info@huk-coburg.de
kontakt@baeckerei-kruetzkamp.de
info@meyermoenchhof.de
kundenbeschwerdestelle@bvr.deVerantwortlich
info@mueller-egerer.de
parparts-backstube@t-online.de
mail@cafe-grimm.de
cafe.michaelis@t-online.de
info@troxler-werkstaetten.de
orga@frauen-u-unternehmen.de
bewerbung@baeckerei-schrunz.de
dergutebaecker@krimphove.de
info@tollkoetter.de
treimer@schmees-ladenbau.de
info@ebaeko.de
info@baeckerei-meier-karlsruhe.de
info@patisserie-ludwig.de
info@konditorei-cafe-jaeck.de
info@dasrieberg.de
info@konditorei-grombacher.de
07244-94771-20backkultur@baeckerei-visel.de
info@fuetterer-baeckerei.de
datenschutz@baeckerei-koehler.de
info@baecker-glutsch.de
kontakt@kondima.de
93info@baeckerei-neff.de
msac.seeger@web.de
info@baeckerei-zipper.de
verwaltung@baeckerei-loescher.de
info@bauer-budde.de
info@konditorei-gingter.de
nadjas-torten@ok.de
hr@roeder-mst.de
tortenmann@gmx.com
info@baeckerei-kamphausen.de
cafe.becker@gmx.de
info@lartsucre.com
hallo@tillys-wiesbaden.de
info@derkleinetortenladen.de
info@gehlhaar-marzipan.de
info@maldaner1859.de
mail@baeckerei-simon.de
info@backhaus-schroeer.de
elisabeth.klein-rost@baeckerei-klein.com
Baeckerei.Am.Ring@gmail.com
kontakt@die-muehlenbaecker.de
info@cafe-dibbern.de
info@konditorei-harm.de
info@knuust.de
info@baeckerei-waeger.de
info@konditorei-suesses-leben.de
kontakt@bio-brotladen.de
info@torten-tarras.de
kontakt@baeckerei-kretzschmar.de
info@baeckerei-kretzschmar.de
mslillystortenzauber@online.de
frankmuschert@yahoo.de
jschlossbauer45@mail.com
antje-luckner@gmx.de
info@voigt-baecker.de
info@baeckerei-groschupf.de
info@schlotfeger.de
info@vollwertbaecker-schneider.de
info@balletshofer.de
info@baeckerei-wolf.de
poststelle@lda.bayern.de
info@lammerskoetter.de
info@vandeleur.nl
info@baeckerei-mannebach.de
info@schauerbrot.de
info@baeckerei-offermanns.de
info@kickartz-printen.de
info@leo-der-baecker.de
info@maalula.com
buero@hochzeitstorten.de
info@noldascafe.de
berg-budenheim@t-online.de
info@baeckerei-preis.de
info@berg-baeckerei.de
info@werners-backstube.de
info@glocken-baeckerei.de
info@baeckerei-engert.de
info@brotagonist.de
info@hamova.de
mail@baeckerei-sprung.de
post@kaffeehaus-koehler.de
kat.kromida@gmail.com
info@cgc-grothe.de
patisseriebarre@gmail.com
info@tortenwichtel.de
info@cafe-leven.de
info@traumtorten-online.de
info@baeckerei-greis.de
dialog@patisserie-m.de
info@chocolatier.de
info@cafewenning.de
info@stadtbaeckerei-kamp.de
jan-seiler@gmx.de
info@baeckerei-rueger.de
mail@cafe-bauer-erfurt.de
gbarkonditorei-cafe.trautwein@t-online.de
info@elmi-backwaren.de
baecker-baum@gmx.de
info@baeckerei-bernecker.de
info@baecker-becker-kassel.de
cafebackhausmarkus@online.de
j.rehermann@cafelange.de
contact@cafe-nenninger.de
info@baeckerei-ruch.de
alexander.kentzler@googlemail.com
baeckerei-rehberg@kabelmail.de
u.deprie@xn--rostocker-kaffeersterei-olc.de
josef.sieveneck@baeckerei-sieveneck.de
presse@von-allwoerden.de
info@nancycake.de
info@niederegger.de
info@cafebiene.de
info@baeckerei-bost.de
info@backstube-hake.de
info@kilim-baklava.de
kontakt@schlechtrimen.de
GeorgBarmscheidt@web.de
info@baeckerei-paffrath.de
info@kleins-backstube.de
info@baeckere-busch.de
info@foerster-baecker.de
info@baeckerei-voosen.de
info@baeckerei-hardt.de
info@cafe-pieper.de
info@baeckerlob.de
bewerbung@baeckerei-busch.de
info@baeckerei-broecker.de
c.hampe@siebendrei.com
info@wellmann-baeckerei.de
info@i-like-no-spam.brinki.de
info@rachels-tortenparadies.de
info@baeckerei-theurer.de
info@cafe-finkhaeuser.de
cafe.kirchner@t-online.de
info@cafe-jannasch.de
adopheide@gmx.de
Ablinkle@aol.com
info@hotel-nothnagel.de
baecker.hofmann@t-online.de
baeckereibreithaupt@arcor.de
hofmann@darmstadt-online.de
kontakt@agethen.com
info@ihr-lieblingsbaecker-johannisbauer.de
hallo@viktoertchen.de
info@as-torten.de
info@patisserie-tanger.de
info@chocolatier-kuhlen.de
otto-bittner@t-online.de
edmund.tockloth@t-online.de
g-becht@g-becht.de
info@annyfood.com
info@baeckerei-busch.de
info@allee-cafe.de
info@baeckerei-behmer.de
info@baeckerei-loescher.de
info@ihr-baecker-schueren.de
Marie.Juskowiak@baeckerei-loescher.de
06221-24606info@konditoreizimmermann.de
info@schneiderback.de
info@heissebaecker.de
geschmack@gundel-heidelberg.de
kontakt@cafe-meisel.deCaf
baeckerei@heiglbeck.de
tortenservice@t-online.de
info@muellerbaeck.net
info@cafe-schroedl.de
info@webers-landbaeckerei.de
hbelz@aol.com
cafe.schwarz@hotmail.de
info@donaueinkaufszentrum.de
kontakt@wagenek.de
webmaster@cafe-maeule.de
gasthaus-odenwald@t-online.de
haug@albkorn.de
info@das-roth.de
info@lang-baeckerei.com
info@baeckerei-eibauer.de
ulm.neue-strasse@coffee-fellows.com
info@baeckerei-wucherer.de
info@baeckerei-kettinger.de
luz@albkorn.de
info@diabetiker-baeckerei.de
info@baeckerei-sporkmann.de
info@baeckerei-benter.de
info@borbaecker.de
info@gasthof-berger.de
il.pasticcino@yahoo.de
info@dolcevita-offenbach.de
kontakt@rauschs-konditorei.de
office@konditorei-hollhorst.de
nfo@stueck-v-glueck.de
glutenfrei@isabella-patisserie.de
info@annareckmann.de
idcake@gmx.de
tortenland@web.de
baeckerei@familie-viola.de
info@jamin-frankfurt.de
info@huckgmbh.de
info@backstube-weller.de
info@kondiback.de
cafe-kling@t-online.de
info@bunca.de
kontakt@hinnerbaecker.com
sales@cafe-siesmayer.de
info@cafe-ernst.de
info@baeckerei-katz.de
kontakt@hotel-cafe-roemer.de
info@kristall-cafe.de
info@baeckerei-czech.de
info@konditorei-fritzenkoetter.de
inantskarachotza@gmail.com
info@baeckerei-olsson.de
info@baeckerei-birkholz.de
info@cafekrummel.de
info@barbarossa-baeckerei.de
uwewolz@yahoo.de
hagel-hanau@arcor.de
bababackerei@hotmail.com
info@schokolaedchen.de
info@ohl-baeckerei.de
info@baeckerei-kolb.de
service@papperts.de
info@mangelmannrosen.de
info@ferdinands-backgenuss.de
christopher-nolte@web.de
hallo@jubel.berlin
info@leta.berlin
marco_sfi@hotmail.de
info@suesseseckchen.de
buero@konditorei-engelmann.de
info@konditorei-krautzig.de
info@heberer.de
Deutschlandberlin.damaskus.konditorei@hotmail.cominfo
info@baeckerei-rauch.de
info@baeckerei-maelzer.de
info@baeckerei-ploetner.de
info@baeckerei-lehmann-berlin.de
info@konditorei-fester.de
impressum@konditorei-laufer.de
mareikeseefluth@gmail.com
infi@baeckereiwahl.de
kontakt@timsbackwaren.de
hochzeitskonditor@konditorei-jaenichen.de
info@henrys-eismanufaktur.de
142bestellung@gelatoclassico.de
info@icedate.de
kontakt@sylter-eismanufaktur.de
prinzeneis@gmail.com
info@die-eisbar.de
info@tante-louise.net
eis@alteatro.de
hallo@mp14.de
info@bayerische-eismanufaktur.de
info@bolleschlotzer.de
service@spoonfulberlin.de
ct.manarin@gmail.com
tomascais@c-c-service.com
info@eismanufaktur-traben.de
info@die-eismanufaktur.net
info@eismanufaktur-soest.de
info@fischereis.de
info@frioli.de
eismanufakturleone@gmail.com
post@dieeisdealer.deUmsatzsteuer
info@oldenburger-eismanufaktur.de
info@schnitzel-point.com
info@ghirloni-eismanufaktur.de
info@hindelanger-kaesemarkt.de
info@krauss-eis.deUSt
info@kugel-eis.de
info@eisbombe.com
info@taberna-eis.de
service@vadirito.de
info@vadirito.de
info@palazzo-sandro.de
kontakt@eiswerk.de
info@cafeluckner.de
laura.vailati9@gmail.com
ginsheim@eiscafevenezia.it
info@hirnfrost-koblenz.de
info@spielzeugmuseum-freinsheim.de
marystar78@hotmail.com
info@eisoma.de
info@eiscafe-de-luca.de
eis-grossi@web.de
maria@et-voila.de
Konktaktinfo@emmathemu.de
info@dellnitz-eis.de
info@plueckthun-eiscafe.de
gelatissimo-bochum@web.de
fabrizio@eiscafe-del-longo.de
marco.schwarz@aol.com
info@allee-center-essen.de
berbati@panciera-eiscafe.de
info@eiscafe-pizzinato.de
info@julo-group.de
info@jannys.com
kikas.eiscafe@gmx.de
info@konditorei-perfekt.de
moerchens@aol.com
eiscafe.behrens@t-online.de
info@eiscafe-kaesemann.de
info@eisdiele-rialto.de
franco@eiscafe-sommariva.de
info@pomodori-potsdam.com
info@seeterrassenfalkensee.com
info@eisdebona.com
info@biancolin.de
eisdiele-laconi@mail.de
Saviane@t-online.de
toscani-eis@t-online.de
gelateria-calabrese@t-online.de
piccin@cafe-venezia.de
info@darino.de
info@eis-primavera.de
info@sanmarco-bochum.de
eiscafeischia@gmail.de
info@eis-mattiuzzi.de
info@eislaedchen-manufaktur.de
fks92@hotmail.de
info@kugelpudel.com
info@kuhbar.de
social@eiscafe-brazil.de
info@eiskeller-hamburg.de
info@eiscafe-lido.de
info@eismanufaktur-brechen.de
willkommen@eis-treff.de
luigi.palopoli@web.de
info@ilcentro-nea.de
luca@eiswagen-luca.de
info@san-remo.de
info@egelosia.de
Pascal@andres-eiscafe.de
eisbirne@t-online.de
eiscafe-bocconcino@web.de
eiscafe-dolomiti@gmx.de
info@dolci-eis.de
ciro@eisfactory.com
info@kaffee-brb.de
rusig@hotmail.com
info@eis-bertram.de
mp.datenschutz@ece.com
info@calabria-mh.de
paolella@gmx.de
cafegelatissimo@googlemail.com
eiscafegirasole@gmail.com
coppola.anna38@gmail.com
info@gelateria-laluna.de
Manolismeo04@gmail.com
kontakt@torten.com
claudiit@live.de
info@eiscafe-promenade.de
mail@expert.de
info@eiscafetiziano.de
info@venezia-oberhausen.de
info@eisstil.de
info@icecadoro.de
info@medienwerk-menden.de
s.a.g.a@freenet.de
dotjal82@hotmail.de
info@haagen-dazs.de
mail@hitzefrei.info
holzi-holzmann@web.de
hagen-eilpe@kuhbar.de
hamm@kuhbar.de
iserlohn@kuhbar.de
werne@kuhbar.de
Lhselbe@gmx.de
gasicmilorad@gmail.com
info@mikas-eisbox.de
annapauly02@gmail.com
eis@gourmeteis.com
eisfreunde@sorellis.de
info@yummys-cafe.de
mail@yoghurt-bar.de
eiscasal@t-online.de
info@daseismeer.de
m121886@hotmail.com
eisbande@freenet.de
info@venezia-schwartau.de
info@eiscafe-polarstern.de
info@eiscafe-eisfieber.de
info@eiscafeflorenz.de
ilgelato@netcologne.de
info@La-Fantastica.de
info@rio-yogurteis.de
info@eiscafe-boethern.de
23751info@eiscafecapri.de
luc@danieli.de
info@san-marco-eiscafe.de
teuflischguteseis@web.de
info@eisdiele-lohschelder.de
info@n-eis.de
eiscafepia@gmail.com
eiscafe-centrale@t-online.de
info@eiscafe-aldo.de
eiswitt@eiswitt.de
info@eiszeit-eis.de
info@eiskonditorei-leiste.de
olas@eiscafe-kuecknitz.de
mauriziosantoro@gmx.net
info@bortolot.de
info@erdbeerenfunck.de
service@eiscafeciaociao.com
info@eisschaetzle.deTel
info@eislaveneta.de
info@pastorelli-kaarst.de
info@eiscafe-creglingen.de
info@pieschels-eisdiele.de
info@sodann-leipzig.de
Emailmail@nordseetraum.de
info@eis-cafe-griem.de
eisparadies-kiel@t-online.de
info@maschener-eiscafe.de
info@campo-eis.de
info@stella-eiscafe.de
c.netto@gmx.de
info@eis-henss.de
info@eiscafe-am-deutschen-eck.de
tsakalouathina6@gmail.com
ik.dirks@t-online.de
kontkat@eiscafecapri.com
kontakt@werk2-biere.de
info@eiscafe-monnalisa.de
eisnart@yahoo.de
info@eiscafe-natale.de
paradisoeis@t-online.de
pateraeis@gmail.com
info@fontanella-eiscafe.de
tirrenomazzotta@web.de
info@eiscafe-zalivani.de
info@ital-eis-europa.de
kontakt@franzetti.de
234-5678-901example@example.com
italoamericano@email.de
info@eiscafe-la-delizia.de
sabinescheibler@googlemail.de
info@eissalon-sagui.de
info@trueand12.com
eiscafeveneziahemmingen@googlemail.com
info@eis-soost.de
post@gelatok.com
afontanella1978@gmail.com
info@eisbegehrt.net
eis-keyl@eis-keyl.de
info@eiscafe-lido-elsenfeld.de
info@casanova-online.net
eis-cafe-boenisch@web.de
info@eiscafe-dacapo.de
kontakt@eiscafedante.de
info@ilgatto.de
urlaub@pension-eis-schumann.de
info@ital-eis-cafe-venezia.de
info@eiscafe-adam.de
metaj-kujtim@freenet.de
info@kaemena-blockland.de
info@calchera.de
marcelofabian@web.de
office@eistortenshop.de
info@beninca.online
info@eiscafecantonati.de
info@gelateriacapani.it
casadelgelato2012@googlemail.com
webmaster@eiscafecortina.de
michel.ralf-heike@t-online.de
info@eiscafe-lorsch.de
dzemo71@googlemail.com
info@eiscafe-etna.de
choclait@web.de
eiscafe.laguglia@gmail.com
milano-arkaden@web.de
email.@facebook.de
kond.peter@t-online.de
th.rotter@t-online.de
neef-confiserie@gmx.de
info@konditorei-wittl.de
kontakt@cafe-schumacher.de
info@konditorei-t-mueller.de
info@confiserie-fischer.de
info@konditorei-dahlmann.de
heikesternemann@gmx.de
kontakt@konditorei-alex-mueller.de
konditoreisternemann@hotmail.com
info@cafe-hemmer.de
info@konditorei-fischer.de
info@pommes-ruhr.de
info@doebbe.de
cafe.fritsche@t-online.de
post@omarosa.de
info@cafe-poggel.de
info@tortenband.de
dobbelstein@cafe-dobbelstein.de
helge-hoyer@web.de
info@kaffeehaus-wessling.de
c.hadyk@gmx.net
konditorei-wenzel@vr-web.de
o-achter@t-online.de
villa-wallner@web.de
confiseriegraff@gmail.com
info@atelier-torten.de
info@bolten-gmbh.de
greatlittlecakery@gmail.com
info@baeckerei-klaesener.de
info@otto-bittner.de
info@u-portalen.de
info@gazipastanesi.com
info@cafe-hilleke.de
caferichter@unitybox.de
95info@konditorei-telgmann.deB
info@zuckerbaecker.com
info@neege.de
kontakt@omma-paulas-kuchentraum.de
info@ruth-online.de
sandra.neuhofen@gmx.de
info@sindern.de
info@konditorei-sirringhaus.de
info@spetsmann.de
info@strassencafe-unionviertel.de
info@konditorei-telgmann.de
info@traumtorten.de
vw@wiacker.de
suesseecke@t-online.de
post@lucka.de
info@biokonditorei-eichel.de
konditorei.melodie@gmail.com
info@konditorei-senf.de
info@patisserie-bach.de
Kontakt@Moebius-Baeckerei.de
info@cafe-herrdegen.de
konditorei@rabien.berlin.de
info@konditorei-jahn.de
info@konditorei-nolda.de
info@walddorfer-zuckerbaecker.de
Info@zucker-zimt-erfurt.de
info@cafe-lund.de
info@baeckerei-brede.de
info@baeckerei-hoenig.de
info@bk-wittorf.de
info@seel-konditorei.de
ulla.glass@cafeamkloster.de
info@cafebechtle.de
info@berriesandbrides.de
konditorei.christmann@web.de
zauberwerkstatt.sz@googlemail.com
dresdnerfeinbaeckerei@web.de
info@der-biokonditor.de
61214info@heyderich.de
info@thomaswenig.de
info@konditorei-buchwald.de
info@konditorei-krengel.de
cafelangensiepen@t-online.de
fressgass@lartsucre.com
kontakt@konditorei-mitterer.de
info@cafe-rall.de
info@marzipanstudio-Rieger.de
cafe.schmidhofer@gmail.com
info@tarteundtoertchen.de
inge.steil@tortenatelier-steil.de
info@villatortenspiel.de
info@cafe-woelke.de
jochen@jochenopitz.de
kontakt@stollensiegel.de
schell@schell-schokoladen.de
info@konditorei-sticherling.de
info@konditorei-elend.de
info@conditorei-steidl.de
info@styleyourcake.de
info@baeckerei-padeffke.de
maria79@online.de
stammhaus@kunder-confiserie.de
info@cafe-schafheutle.de
info@schell-schokoladen.de
info@ingwersen-sylt.de
info@konditorei-gerads.de
frieda@baeckereihaupt.de
kontakt@der-biobaecker.de
info@klugs-backstube-gadebusch.de
info@konditorei-cafe-koester-ratekau.de
info@conditorei-muench.de
mail@persienhaus.de
info@schokodeern.de
info@zuckerammarkt.de
karljaeger@franken-online.de
info@patisserie.de
patrick.amendt@arcor.de
info@konditorei-battke.de
info@bounours.de
info@cafe-nederkorn.de
christina.reiplinger@outlook.de
cc@conditcouture.com
info@confiserie-schriefer.de
info@sweet-artist.de
service@conditorei-eube.de
info@fototorten.de
info@kuchenwerkstatt.de
info@cafe-frueholz.de
info@giesselmanns.de
info@cafe-haberstroh.de
info@cafehaertl.de
unplugged@hartundherzlich-patisserie.com
info@konditorei-kaffeehaus.de
cafe_helmreich@web.de
cafeschien@gmail.com
kontakt@konditorei-freudenberg.de
info@festtagskonditorei.de
okadakanako@aol.com
info@konditorei-fritzsche.de
info@torten-pralinen.de
info@cafe-mangold.de
info@milkau.de
tortenwelt@t-online.de
info@cafe-saumon.de
info@cafe-schierhorn.de
info@siegel-backkultur.de
info@der-tortenschmied.de
info@eifelkonditorei.de
info@werkstatt-der-suesse.de
info@cafe-kraume.de
hans-heinrich.reinartz@gmx.de
info@schapers-back-shop.de
info@baeckerei-zimmer.de
contact@babka-und-krantz.de
mail@poeth.de
info@cafe-roethgen.de
schreibensieuns@konditorei-schindel.de
info@konditorei-cafe-schreiber.de
info@sugarbird-cupcakes.de
info@cafe-vetter-marburg.de
konditorei-willert@web.de
info@tortenfee.de
info@ludwig-harter.de
info@konditorei-nick.de
info@friwi.de
mohrenkoepfle@t-online.de
info@cafe-reinhardt.de
cafe-rothe@gmx.de
info@baeckerschlueter.de
sievert-geesthacht@t-online.de
info@cafe-kinnel.de
baeckerei-simon@t-online.de
kontakt@konditorei-nowak.de
schaepe@swschwedt.de
info@konditorei-klingelhoefer.de
krauss@konditorei-rittrich.de
webmaster@baeckereihartmann.de
info@kroenner.com
info@konditorei-moennig.deAdresse
info@konditorei-schiller.de
harald@baeckerei-stammler.de
thomas.nitt@wtnet.de
info@die-suesse-fee.de
Info@Cafe-Eber.de
service@konditorei-bauerfeind.de
CafeMiddelberg@aol.com
info@himmlisch.suess.de
info@toertchentoertchen.de
info@baeckerei-nitt.de
info@gugelhupf-berlin.com
info@steigleiter.de
mail@konditorei-popp.de
kundenservice@meine-baecker.de
baeckereischmidt@freenet.de
tilsengmbh@t-online.de
kontakt@baeckerei-boldt.de
info@cafe-fiedler.de
info@baeckerei-peters.de
stefanvonhartz@t-online.de
hallo@herrmax.de
info@kadatz.de
service@jb.de
info@konditorei-lindtner.de
bestellung-schaepe@swschwedt.de
info@rohlfsbaeckerei.de
st.paula@hamburg.de
info@stadtbaeckerei-stralsund.de
grimminger@t-online.de
info@holzbaecker-jost.de
info@baeckerei-ulfers.de
brezenbeck@web.de
j.hartmann@augustinum.de
info@yeanshalle.de
info@rabbel.com
713info@cronundlanz.de
info@baeckerei-friedrich.de
info@konditorei-heinemann.de
info@konditorei-holland-moritz.de
info@hotelmaass.de
info@muenchs-backstube.de
mail@patisserie-elysee.de
service@weber-weiss.de
info@joliejour-confisserie.de
torten@tortenbutik.de
tammii@gmx.de
info@baeckerei-meyns.de
stern-laage@t-online.de
info@baecker-andresen.de
info@von-allwoerden.de
m.beyer@baeckerei-beyer.de
info@baeckerei-hagelstein.de
info@wt-schmidt.de
info@baeckerei-konditorei-hesse.de
info@baeckerei-kolls.de
hansen-langstedt@web.de
9890-60E-Mailbernhard.spaeth@baeckerei-narr.deFilialenIn
kontakt@baeckerei-zimmer.de
baeckereibrandt@aol.com
info@konditorei-braun.de
"""  # ← Add your full list between the triple quotes

# --- Script Start ---

# Split into lines, clean, and normalize
email_lines = raw_emails.strip().splitlines()

unique_emails = set()
cleaned_emails = []

# Normalize, deduplicate, and remove trailing punctuation
for email in email_lines:
    clean_email = email.strip().lower().rstrip('.').rstrip(',')
    if clean_email and clean_email not in unique_emails:
        unique_emails.add(clean_email)
        cleaned_emails.append(clean_email)

# Remove emails that end with .gov or contain certain keywords
excluded_keywords = ['urzad', 'nieruchomosci', 'inwestycje', 'grzybki', 'travel', 'redakcja' 'radio']
filtered_emails = [
    email for email in cleaned_emails
    if not email.endswith('.gov') and not any(keyword in email for keyword in excluded_keywords)
]

# Print results
for email in filtered_emails:
    print(email)